-- ==============================================================================
-- THE WINDOW DOCTOR - SUPABASE DATABASE SEED DATA
-- ==============================================================================

-- 1. Service Categories
INSERT INTO service_categories (id, slug, name_en, name_th, description, icon_name, sort_order) VALUES
('11111111-1111-1111-1111-111111111111', 'glass-repairs', 'Glass & Glazing Repairs', 'งานซ่อมกระจกและซีลยาง', 'Misted glass, broken pane replacements, draughts & lock repair', 'Sparkles', 1),
('22222222-2222-2222-2222-222222222222', 'windows', 'Modern Window Installations', 'งานติดตั้งหน้าต่างโมเดิร์น', 'Casement, Flush Sash, Sliding Sash in uPVC and Aluminium', 'Grid', 2),
('33333333-3333-3333-3333-333333333333', 'doors', 'Stylish Entrance & Patio Doors', 'งานติดตั้งประตูบ้านและระเบียง', 'High-security Composite, Panoramic Bi-fold, and French Doors', 'DoorClosed', 3),
('44444444-4444-4444-4444-444444444444', 'conservatories', 'Warm Roof Conservatories', 'งานปรับปรุงหลังคาเรือนกระจก', 'Tiled thermal warm roof conversions & lantern skylights', 'Home', 4),
('55555555-5555-5555-5555-555555555555', 'balustrades', 'Bespoke Glass Balustrades', 'ระเบียงและราวกันตกกระจกเปลือย', 'Frameless structural glass balustrades & Juliette balconies', 'Shield', 5)
ON CONFLICT (slug) DO NOTHING;

-- 2. Services
INSERT INTO services (id, category_id, slug, title, headline, short_description, full_content, hero_image_url, features, specifications, base_price_estimate, price_unit, warranty_years, is_fensa_certified) VALUES
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '11111111-1111-1111-1111-111111111111', 'misted-glass-repair', 'Misted Glass & Seal Failure Repair', 'Replace the Glass, Not the Frame — Save Up to 70%', 'Restore crystal-clear views and thermal efficiency without the expense of replacing your existing window frames.', 'Over time, double glazing unit seals can deteriorate due to weather exposure, allowing moisture to seep between the glass panes. Our master glaziers precisely measure and replace solely the sealed insulated glass unit (IGU), retaining your original frames and saving you hundreds of pounds.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4PgLGqLJswj_yOE9Fp-h7Bh-0gB3SEGKW6wM__fhYsI1vcAZwqvKhgzpVL7CPX7XDHfvLEFLucGEy4uNrBRgE-6Ygcy_HksxKYiVtZxOFrjkRG5UiALFDyTnqEFSdiMMHVQtQIoDIgwDQLyuJAjYBogUwBNPAh0jSMBy_zkHmL9gRXfOW6qtVeyd7XAcVNUXYynC-N2W5g5e1oWBK8e7f5qY9lqco1Xmr5MekrfBHfzcqTU0EIh2I', '["Save 50-70% vs complete window replacement", "Argon-gas filled for maximum A++ energy rating", "Quick and clean installation in under 1 hour per unit", "10-Year Anti-Fog Guarantee", "Toughened & Acoustic glass options available"]'::jsonb, '{"u_value": "1.1 W/m²K", "glass_type": "Pilkington Optitherm Low-E", "gas_filling": "90% Argon Gas", "warm_edge_spacer": "Swissspacer Ultimate"}'::jsonb, 95.00, 'per unit', 10, true),

('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '22222222-2222-2222-2222-222222222222', 'modern-windows', 'Modern Energy-Efficient Windows', 'Architectural Elegance with A++ Thermal Performance', 'Precision-crafted uPVC and slimline aluminium windows designed to keep your home warm, quiet, and secure.', 'Upgrade your property with our bespoke window collection. Whether you prefer classic flush sash frames for period cottages or ultra-slim architectural aluminium profiles for contemporary residences, our installations feature multi-point locking systems and market-leading acoustic insulation.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9Fjn6wLLJZk7YeTa18NvqtxVCAuCLsPnhE3EOon6a9RSl8DqWeJ6DGpPN3B6yXvnBbK_8OP57skrmnRE00KFwtYNY4-Po01ZpW2IZL8dhW-KTZEIwNqYHLH2ZMj0dT9_rIRZNzmVr41RmOTyB57SKAxZYM20vaj7zwWoJac6g65mlm_vIk0VGIAHhRm2i2Cl3os08pjvua_ekNlYnUBydzWripfsDHkuMnFFqvYRAnr3YkGB7oUYnD2ugQDdU-jkp1w', '["A++ Energy Efficiency Ratings", "Secured by Design PAS 24 multi-point locks", "Sound reduction up to 42dB", "Dual-colour frame options (Anthracite, Heritage Cream, Oak)", "FENSA Certified with 10-Year Insurance Guarantee"]'::jsonb, '{"frame_material": "uPVC & Slimline Aluminium", "security_standard": "PAS 24 / Secured by Design", "noise_reduction": "Up to 42dB", "glazing_options": "Double (28mm) or Triple (44mm)"}'::jsonb, 380.00, 'per window', 10, true),

('cccccccc-cccc-cccc-cccc-cccccccccccc', '33333333-3333-3333-3333-333333333333', 'stylish-doors', 'Bespoke Composite & Bi-fold Doors', 'Make a Grand Entrance with Uncompromising Security', 'Premium composite front doors and seamless panoramic bi-fold patio doors engineered for British weather.', 'Transform your living space with our premium door collection. Our solid-core composite front doors provide exceptional thermal efficiency and multi-point police-approved security. For garden transitions, our aluminium bi-folding and sliding patio doors create smooth, effortless indoor-outdoor living.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCbFijkuiNQPNPRi1odFsC7paCR0AXJXuNyP_Cb-JqkwnbIBuxNVG_Mr4zRuk1fFgPRzkjXxUQDu1iwIRZwDTi_kG3eU_TAx1phbyAir4OMCgkYVrb2Ra6IqO5hZ4FWoxvajQ6TOXNO4G06w-YMm3WsfPJLn7rQcPSbwLR58mHGQMfgkDOb03V4gE6s7NnXR-Rvv2O19FLhqGQ2VYKhJiLmetWImwmvPyDc9o1FRF1oczJR0EkIlBkf', '["48mm Solid timber core composite doors", "3-Star Ultion diamond security cylinders", "Smooth glide stainless steel bi-fold rollers", "Low-threshold options for wheelchair accessibility", "Weather-tested against gale-force British storms"]'::jsonb, '{"core_thickness": "48mm solid timber core", "lock_rating": "3-Star Ultion Diamond", "weather_resistance": "BS 6375-1 passed", "finish": "Scratch-resistant GRP skin"}'::jsonb, 750.00, 'per door', 10, true),

('dddddddd-dddd-dddd-dddd-dddddddddddd', '44444444-4444-4444-4444-444444444444', 'warm-roof-conservatories', 'Warm Roof Conservatory Conversions', 'Transform Your Conservatory into an All-Year Living Room', 'Replace your freezing winter / boiling summer roof with a lightweight, highly insulated tiled warm roof system.', 'Reclaim your conservatory for 365 days a year. Our SupaLite and Guardian warm roof systems replace outdated polycarbonate or leaking glass roofs with lightweight slate/tile finishes and high-performance multilayer insulation, delivering U-values as low as 0.15 W/m²K.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCbFijkuiNQPNPRi1odFsC7paCR0AXJXuNyP_Cb-JqkwnbIBuxNVG_Mr4zRuk1fFgPRzkjXxUQDu1iwIRZwDTi_kG3eU_TAx1phbyAir4OMCgkYVrb2Ra6IqO5hZ4FWoxvajQ6TOXNO4G06w-YMm3WsfPJLn7rQcPSbwLR58mHGQMfgkDOb03V4gE6s7NnXR-Rvv2O19FLhqGQ2VYKhJiLmetWImwmvPyDc9o1FRF1oczJR0EkIlBkf', '["U-Value of 0.15 W/m²K — warmer in winter, cooler in summer", "Building Regulations Compliant with certification", "Integrated LED spotlights and roof lantern skylights", "Lightweight structural aluminium frame", "Dramatically reduces rain noise"]'::jsonb, '{"u_value": "0.15 W/m²K", "structure": "Lightweight Structural Aluminium", "tiles": "Tapco Synthetic Slate / Metrotile", "compliance": "Full Building Regs JHAI Approved"}'::jsonb, 3500.00, 'per installation', 10, true),

('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', '55555555-5555-5555-5555-555555555555', 'glass-balustrades', 'Bespoke Frameless Glass Balustrades', 'Unobstructed Panoramic Views & Modern Luxury', 'Toughened laminated structural glass railings for balconies, staircases, decking, and terraces.', 'Add architectural brilliance and safety to your home with our bespoke glass balustrades. Manufactured using 17.5mm or 21.5mm toughened laminated glass with corrosion-resistant 316 marine-grade stainless steel hardware, providing seamless views without compromising on structural rigidity.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4PgLGqLJswj_yOE9Fp-h7Bh-0gB3SEGKW6wM__fhYsI1vcAZwqvKhgzpVL7CPX7XDHfvLEFLucGEy4uNrBRgE-6Ygcy_HksxKYiVtZxOFrjkRG5UiALFDyTnqEFSdiMMHVQtQIoDIgwDQLyuJAjYBogUwBNPAh0jSMBy_zkHmL9gRXfOW6qtVeyd7XAcVNUXYynC-N2W5g5e1oWBK8e7f5qY9lqco1Xmr5MekrfBHfzcqTU0EIh2I', '["17.5mm - 21.5mm Toughened Laminated Safety Glass", "Duplex 2205 & 316 Marine-grade stainless steel", "Compliant with BS 6180:2011 building codes", "Easy-clean hydrophobic nano-coating available", "Internal staircase & external garden balcony options"]'::jsonb, '{"glass_thickness": "17.5mm - 21.5mm Toughened Laminated", "hardware_grade": "Marine Grade 316 / Duplex 2205", "loading_standard": "0.74kN - 1.5kN (BS 6180:2011)"}'::jsonb, 220.00, 'per linear metre', 10, true)
ON CONFLICT (slug) DO NOTHING;

-- 3. Service Areas & Postcodes
INSERT INTO service_areas (id, town_name, county, response_time_hours, emergency_available, free_survey) VALUES
('area-1', 'Bicester & Bucknell', 'Oxfordshire', 2, true, true),
('area-2', 'Oxford City & Suburbs', 'Oxfordshire', 4, true, true),
('area-3', 'Banbury & Surrounds', 'Oxfordshire', 4, true, true),
('area-4', 'Kidlington & Woodstock', 'Oxfordshire', 4, true, true),
('area-5', 'Brackley & Buckingham', 'Buckinghamshire', 6, true, true),
('area-6', 'Witney & Cotswolds East', 'Oxfordshire', 6, true, true),
('area-7', 'Thame & Aylesbury Border', 'Oxfordshire', 6, true, true)
ON CONFLICT DO NOTHING;

INSERT INTO postcodes (postcode_prefix, area_id, region_name) VALUES
('OX25', 'area-1', 'Bicester North, Bucknell, Ambrosden, Weston-on-the-Green'),
('OX26', 'area-1', 'Bicester Central, Kingsmere, Highfield, Bure Park'),
('OX27', 'area-1', 'Bicester East, Fritwell, Marsh Gibbon, Stratton Audley'),
('OX1', 'area-2', 'Central Oxford, Grandpont, New Hinksey'),
('OX2', 'area-2', 'North Oxford, Summertown, Wolvercote, Jericho'),
('OX3', 'area-2', 'Headington, Marston, Barton'),
('OX4', 'area-2', 'East Oxford, Cowley, Iffley, Rose Hill'),
('OX5', 'area-4', 'Kidlington, Yarnton, Begbroke, Gosford'),
('OX15', 'area-3', 'Bloxham, Deddington, Hook Norton, Sibford Gower'),
('OX16', 'area-3', 'Banbury Town, Neithrop, Hardwick, Grimsbury'),
('OX28', 'area-6', 'Witney Central, Cogges, Ducklington'),
('OX29', 'area-6', 'Eynsham, Long Hanborough, Freeland'),
('OX9', 'area-7', 'Thame, Moreton, Towersey'),
('NN13', 'area-5', 'Brackley, Croughton, Evenley, Turweston'),
('MK18', 'area-5', 'Buckingham, Tingewick, Gawcott')
ON CONFLICT (postcode_prefix) DO NOTHING;

-- 4. Projects Portfolio
INSERT INTO projects (id, service_id, title, location_city, completion_year, summary, challenge_description, solution_description, specifications, before_image_url, after_image_url, is_featured, sort_order) VALUES
('proj-1', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Complete Misted Double Glazing Restoration', 'Bicester, Oxfordshire', '2024', 'Restored 14 misted and condensation-damaged double glazing units in a 1990s detached family home, retaining original mahogany frames.', 'The homeowner suffered from severe cloudiness between glass panes blocking garden views and reducing heating efficiency. Competitor quotes suggested replacing all window frames costing over £9,000.', 'The Window Doctor surveyed the property, precisely measured all 14 units, and manufactured custom Argon-filled Pilkington Optitherm double glazed units. All units were replaced in a single day at less than one-third of the competitor cost.', '["14 High-performance Argon sealed units", "Pilkington Optitherm Low-E Coating", "Swissspacer warm edge thermal spacers", "Total cost saving: 68% vs new frames", "Zero disruption to interior decoration"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4PgLGqLJswj_yOE9Fp-h7Bh-0gB3SEGKW6wM__fhYsI1vcAZwqvKhgzpVL7CPX7XDHfvLEFLucGEy4uNrBRgE-6Ygcy_HksxKYiVtZxOFrjkRG5UiALFDyTnqEFSdiMMHVQtQIoDIgwDQLyuJAjYBogUwBNPAh0jSMBy_zkHmL9gRXfOW6qtVeyd7XAcVNUXYynC-N2W5g5e1oWBK8e7f5qY9lqco1Xmr5MekrfBHfzcqTU0EIh2I', 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9Fjn6wLLJZk7YeTa18NvqtxVCAuCLsPnhE3EOon6a9RSl8DqWeJ6DGpPN3B6yXvnBbK_8OP57skrmnRE00KFwtYNY4-Po01ZpW2IZL8dhW-KTZEIwNqYHLH2ZMj0dT9_rIRZNzmVr41RmOTyB57SKAxZYM20vaj7zwWoJac6g65mlm_vIk0VGIAHhRm2i2Cl3os08pjvua_ekNlYnUBydzWripfsDHkuMnFFqvYRAnr3YkGB7oUYnD2ugQDdU-jkp1w', true, 1),

('proj-2', 'cccccccc-cccc-cccc-cccc-cccccccccccc', 'Anthracite Aluminium Bi-Fold Doors Installation', 'Summertown, Oxford', '2024', 'Installed 5-panel panoramic aluminium bi-fold doors creating seamless open-plan flow to the landscaped garden patio.', 'The client wanted to replace old draughty French doors with a large architectural glass opening while maintaining maximum insulation and effortless sliding motion.', 'Engineered a structural lintel opening and fitted bespoke Anthracite Grey (RAL 7016) thermal-break aluminium bi-fold doors with flush threshold and child-safe anti-slam magnetic catches.', '["5-Panel Schuco aluminium profile system", "Low-emissivity solar control double glazing", "Flush weathered rebated threshold", "3-Star Ultion high security locks", "Full FENSA registration & certificate"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4PgLGqLJswj_yOE9Fp-h7Bh-0gB3SEGKW6wM__fhYsI1vcAZwqvKhgzpVL7CPX7XDHfvLEFLucGEy4uNrBRgE-6Ygcy_HksxKYiVtZxOFrjkRG5UiALFDyTnqEFSdiMMHVQtQIoDIgwDQLyuJAjYBogUwBNPAh0jSMBy_zkHmL9gRXfOW6qtVeyd7XAcVNUXYynC-N2W5g5e1oWBK8e7f5qY9lqco1Xmr5MekrfBHfzcqTU0EIh2I', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCbFijkuiNQPNPRi1odFsC7paCR0AXJXuNyP_Cb-JqkwnbIBuxNVG_Mr4zRuk1fFgPRzkjXxUQDu1iwIRZwDTi_kG3eU_TAx1phbyAir4OMCgkYVrb2Ra6IqO5hZ4FWoxvajQ6TOXNO4G06w-YMm3WsfPJLn7rQcPSbwLR58mHGQMfgkDOb03V4gE6s7NnXR-Rvv2O19FLhqGQ2VYKhJiLmetWImwmvPyDc9o1FRF1oczJR0EkIlBkf', true, 2),

('proj-3', 'dddddddd-dddd-dddd-dddd-dddddddddddd', 'Lightweight Warm Roof Conservatory Conversion', 'Banbury, Oxfordshire', '2024', 'Converted an unusable 18-year-old Victorian polycarbonate conservatory into a year-round heated garden room.', 'The conservatory was freezing in winter and unbearably hot in summer, with loud rain resonance rendering it completely unusable for 8 months of the year.', 'Removed old polycarbonate roof and installed a custom insulated SupaLite warm roof system finished with Tapco slate tiles, two Velux roof windows, and internal vaulted ceiling with LED downlights.', '["U-Value reduced from 3.2 to 0.15 W/m²K", "Tapco Slate tiles matched to existing house", "2x Velux solar-powered roof windows", "Fully certified by Building Control", "Added estimated £18,000 to property value"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4PgLGqLJswj_yOE9Fp-h7Bh-0gB3SEGKW6wM__fhYsI1vcAZwqvKhgzpVL7CPX7XDHfvLEFLucGEy4uNrBRgE-6Ygcy_HksxKYiVtZxOFrjkRG5UiALFDyTnqEFSdiMMHVQtQIoDIgwDQLyuJAjYBogUwBNPAh0jSMBy_zkHmL9gRXfOW6qtVeyd7XAcVNUXYynC-N2W5g5e1oWBK8e7f5qY9lqco1Xmr5MekrfBHfzcqTU0EIh2I', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCbFijkuiNQPNPRi1odFsC7paCR0AXJXuNyP_Cb-JqkwnbIBuxNVG_Mr4zRuk1fFgPRzkjXxUQDu1iwIRZwDTi_kG3eU_TAx1phbyAir4OMCgkYVrb2Ra6IqO5hZ4FWoxvajQ6TOXNO4G06w-YMm3WsfPJLn7rQcPSbwLR58mHGQMfgkDOb03V4gE6s7NnXR-Rvv2O19FLhqGQ2VYKhJiLmetWImwmvPyDc9o1FRF1oczJR0EkIlBkf', true, 3)
ON CONFLICT DO NOTHING;

-- 5. Customer Reviews
INSERT INTO customer_reviews (project_id, customer_name, customer_location, service_category, rating, review_title, review_text, is_verified, review_date) VALUES
('proj-1', 'David & Sarah Henderson', 'Kingsmere, Bicester', 'Misted Glass Repair', 5, 'Saved us thousands on our windows!', 'Other companies told us we had to replace all window frames at huge expense. The Window Doctor came out the next day, surveyed the seals, and replaced only the glass. Fast, immaculate, and our home is warm again!', true, '2024-10-15'),
('proj-2', 'Dr. Edward Thorne', 'Summertown, Oxford', 'Bi-Fold Doors Installation', 5, 'Exceptional craftsmanship and precision', 'From the initial survey to the final fitment, the team demonstrated master-level skill. The bi-folds glide with one finger and transformed our rear extension. Highly recommended.', true, '2024-11-02'),
('proj-3', 'Mrs. Gillian Wright', 'Bloxham, Banbury', 'Warm Roof Conversion', 5, 'We finally have our living space back', 'We can now sit in our conservatory even in sub-zero January weather. The sound of rain is completely muted, and the lighting looks stunning. 40 years of experience truly shows.', true, '2024-11-20'),
(NULL, 'Mark & Claire Davies', 'Kidlington, Oxfordshire', 'Composite Door & Windows', 5, 'Prompt, polite and outstanding quality', 'Replaced our dated front door with a solid core composite and fitted new triple glazed casement windows. Great communication from the office and clean, tidy installers.', true, '2024-12-05');
