import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9ff",
        "surface-dim": "#d0daf0",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d9e3f9",
        "on-surface": "#121c2c",
        "on-surface-variant": "#44464e",
        "inverse-surface": "#273141",
        "inverse-on-surface": "#ebf1ff",
        outline: "#75777f",
        "outline-variant": "#c5c6cf",
        "surface-tint": "#4c5e86",
        primary: {
          DEFAULT: "#00081e",
          foreground: "#ffffff",
          container: "#0a1f44",
          "on-container": "#7687b2",
          fixed: "#d9e2ff",
          "fixed-dim": "#b4c6f4",
          "on-fixed": "#041a3f",
          "on-fixed-variant": "#34466d",
        },
        "inverse-primary": "#b4c6f4",
        secondary: {
          DEFAULT: "#775a19",
          foreground: "#ffffff",
          container: "#fed488",
          "on-container": "#785a1a",
          fixed: "#ffdea5",
          "fixed-dim": "#e9c176",
          "on-fixed": "#261900",
          "on-fixed-variant": "#5d4201",
        },
        tertiary: {
          DEFAULT: "#070a0a",
          foreground: "#ffffff",
          container: "#1e2122",
          "on-container": "#868889",
          fixed: "#e1e3e4",
          "fixed-dim": "#c5c7c8",
          "on-fixed": "#191c1d",
          "on-fixed-variant": "#454748",
        },
        error: {
          DEFAULT: "#ba1a1a",
          foreground: "#ffffff",
          container: "#ffdad6",
          "on-container": "#93000a",
        },
        background: "#f9f9ff",
        "on-background": "#121c2c",
        "surface-variant": "#d9e3f9",
        brand: {
          navy: "#00081E",
          navyLight: "#0A1F44",
          gold: "#C5A059",
          goldLight: "#FED488",
          goldDark: "#775A19",
          darkBg: "#020713",
        },
      },
      fontFamily: {
        headline: ["var(--font-inter)", "var(--font-hanken)", "var(--font-prompt)", "sans-serif"],
        display: ["var(--font-inter)", "var(--font-hanken)", "var(--font-prompt)", "sans-serif"],
        body: ["var(--font-inter)", "var(--font-work-sans)", "var(--font-prompt)", "sans-serif"],
        label: ["var(--font-inter)", "var(--font-work-sans)", "var(--font-prompt)", "sans-serif"],
        prompt: ["var(--font-prompt)", "sans-serif"],
        inter: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        none: "0px",
        xs: "4px",
        sm: "6px",
        md: "8px",
        DEFAULT: "10px",
        lg: "12px",
        xl: "14px",
        "2xl": "16px",
        "3xl": "20px",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "80px",
        "section-gap": "120px",
      },
      boxShadow: {
        hard: "2px 2px 0px 0px rgba(0, 8, 30, 0.2)",
        "hard-gold": "2px 2px 0px 0px rgba(119, 90, 25, 0.4)",
        card: "0 2px 8px -2px rgba(18, 28, 44, 0.06), 0 1px 4px -1px rgba(18, 28, 44, 0.04)",
        glow: "0 0 25px -5px rgba(197, 160, 89, 0.25)",
      },
    },
  },
  plugins: [],
};

export default config;

